//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud77
{
    using System;
    using System.Collections.Generic;
    
    public partial class crud77
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> age { get; set; }
    }
}
